djangoordersystem/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('system.urls', namespace='system'))
]

system/urls.py
from django.urls import path
from .views import home_view, login_view, confirm_order, logout_view, register_view, order_summary, add_to_cart

app_name = 'system'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('', home_view, name='home'),
    path('order', order_summary, name='order-summary'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('confirm-order', confirm_order, name='confirm-order')
]

system/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import redirect, reverse



class Product(models.Model):

    product_name = models.CharField(max_length=255)
    price = models.FloatField()
    discounted = models.FloatField()
    description = models.TextField(blank=True, null=True)
    slug = models.SlugField()

    product_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product_name

    def add_to_cart(self):
        return reverse('system:add-to-cart', kwargs={'slug':self.slug})

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    order_status = models.BooleanField(default=False)
    order_started = models.DateTimeField(auto_now_add=True)
    shipped = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user}"


class OrderProduct(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    confirmed = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)

    added_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.quantity} units of {self.product.product_name}"

system/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


class RegisterForm(UserCreationForm):

    # Adding a mandatory email field to the UserCreationForm
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

system/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RegisterForm as RF
from django.http import HttpResponse
from django.contrib.auth import login as authlogin
from django.contrib.auth import logout as authlogout
from django.contrib.auth import authenticate as auth
from django.contrib.auth.decorators import login_required as login_required
from .models import Product, Order, OrderProduct
from django.db.models import Avg, Sum, Count

@login_required
def home_view(request):

    context = {'objects': Product.objects.all() }

    return render(request, 'home.html', context)


@login_required
def logout_view(request):
    authlogout(request)

    return redirect('system:login')


def login_view(request):

    if request.method == 'POST':

        user = auth(request, 
        username=request.POST.get('username'),
        password=request.POST.get('password'))

        if user is not None:
            authlogin(request, user)
            return redirect('system:home')
        else:
            return HttpResponse('You have failed to login.')
    elif request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('system:home')

    return render(request, 'login.html')



def register_view(request):

    if request.method == 'POST':
        form = RF(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('Success')
            
    else:
        form = RF()

    context = {'form': form}
    
    return render(request, 'register.html', context)

@login_required
def order_summary(request):

    orders = OrderProduct.objects.filter(user=request.user)

    unconfirmed_orders = OrderProduct.objects.filter(user=request.user, confirmed=False)

    total = unconfirmed_orders.aggregate(Sum('product__price'))

    items = unconfirmed_orders.aggregate(Sum('quantity'))

    context = {'data': orders, 'total': total, 'items': items}

    return render(request, 'summary.html', context)


@login_required
def add_to_cart(request, slug):

    # Store the product object, given a slug
    product = get_object_or_404(Product, slug=slug)

    # Create or store Order object based on conditional
    order_queryset = Order.objects.filter(user=request.user, order_status=False)
    
    if order_queryset.exists():
        order = order_queryset[0]
    else:
        order = Order.objects.create(user=request.user)
    
    # Create OrderProduct given the above objects
    order_product = OrderProduct.objects.create(user=request.user, 
                                                product=product, 
                                                order=order)

    return redirect('system:order-summary')



@login_required
def confirm_order(request):

    # Check for unconfirmed product level orders
    order_queryset = OrderProduct.objects.filter(user=request.user, confirmed=False)
    
    if order_queryset.exists():

        # First get the order ID
        order_id = order_queryset[0].order.id
        print(order_id)

        # Update ProductOrders Objects
        for order_product in order_queryset:
            order_product.confirmed = True
            order_product.save()
        
        # Update the Order Object
        order = Order.objects.filter(id=order_id)[0]
        order.order_status = True
        order.save()

    else:
        print("No outstanding items")

    return redirect('system:order-summary')

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
 <style>
 code {
   background-color:'transparent' !important;
   color: rgb(28, 140, 148);
   }
 </style>
  </head>
  <body>
{% block content %}
{% endblock %}
  </body>
</html>

templates/home.html
{% extends 'base.html' %}


{% block content %}
<section class="section">
    <section class="container">
        <h1 class="title">Products</h1>
        <section class="columns is-multiline">
            {% for o in objects %}
            <div class="column is-one-third">
            <article class="notification">
                <div class="content">
                    <h3>{{ o.product_name }}</h3>
                    <p>{{ o.description }}</p>
                    <p><code>Price ${{ o.price }}</code></p> 
                    <p><code>Discounted Price ${{ o.discounted }}</code></p>
                    
                    <p><code>Added: {{ o.product_created }}</code></p>
                    <p><a href="{{ o.add_to_cart }}" class="button is-small is-primary is-outlined">Add 1 unit to cart</a></p> 
                </div>

            </article>
        </div>
            {% endfor %}
        </section>
        

    </section>
</section>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}


{% block content %}
<section class="section">
    <section class="container">
        <h1 class="title">Login</h1>
        <form action="" method="POST" class="form">
                {% csrf_token %}
            <label class="label">Username</label>
            <input type="text" name="username">

            <label class="label">Password</label>
            <input type="password" name="password">

            <button type="submit" class="button is-link is-outlined">Login</button>
        </form>
    </section>
</section>
{% endblock content %}

templates/register.html
{% extends 'base.html' %}


{% block content %}
<section class="section">
    <section class="container">
        <h1 class="title">Register</h1>
        <form action="" class="form" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="button is-link is-outlined">Register</button>
        </form>
    </section>
</section>
{% endblock content %}

templates/summary.html
{% extends 'base.html' %}


{% block content %}
<section class="section">
    <section class="container">
        <div class="content">
        <h1 class="title">Order Summary</h1>
        <table class="table is-striped" style="font-size: .9rem;">
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Product Price</th>
                    <th>Product Status</th>
                    <th>Order ID</th>
                    <th>Order Started</th>
                    <th>Order Confirmed</th>
                    <th>Product Confirmed</th>
                </tr>
            </thead>
            <tbody>
            {% for d in data %}
                <tr>
                    <td>{{d.product.product_name}}</td>
                    <td style="font-family: monospace;">${{d.product.price}}</td>
                    <td style="font-family: monospace;">{{d.added_on}}</td>
                    <td style="font-family: monospace;">{{d.order.id}}</td>
                    <td style="font-family: monospace;">{{d.order.order_started}}</td> 

                    {% if d.order.order_status %} 
                        <td><p class="tag is-success">Confirmed</p></td>
                    {% else %}
                    <td><p class="tag is-danger">Unconfirmed</p></td>
                    {% endif %}
                    
                    {% if d.confirmed %} 
                        <td><p class="tag is-success">Confirmed</p></td>
                    {% else %}
                     <td><p class="tag is-danger">Unconfirmed</p></td>
                    {% endif %}

                </tr>
            {% endfor %}
            </tbody>
        </table>
        <p>Order Total: ${{total.product__price__sum}}</p>
        <p>Number of items in order: {{items.quantity__sum}}</p>
        <a href="{% url 'system:confirm-order' %}" class="button is-primary is-outlined">Confirm Order</a>
    </div>
    </section>
</section>
{% endblock content %}